name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true
[observability]
enabled = true
[[d1_databases]]
binding = "db"
database_name = "mail"
database_id = "9be2722a-a88b-4873-ac70-b0f95d69d9e9"
[[kv_namespaces]]
binding = "kv"
id = "2c8c019caf0b48e78067ea58635c6e32"
[[r2_buckets]]
binding = "r2"
bucket_name = "mail"
[[send_email]]
name = "email"
[ai]
binding = "ai"
[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true
[triggers]
crons = ["0 16 * * *"]
[vars]
#ai_model = ""
#analysis_cache = false
#orm_log = false
#domain = []
#admin = ""
#jwt_secret = ""
[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
   
